// Static build for GitHub Pages.
//
// The app is a Node server (node:http + SQLite), which Pages cannot run. This
// script snapshots the live API into flat JSON and ships the SAME frontend
// files unmodified; a small shim (static-api.js) intercepts window.fetch and
// answers the app's /api/... calls from that snapshot, doing the sort/filter
// the server would have done. So the deployed page runs the real app.js
// against real collected data — it just can't re-collect.
//
// Usage: node scripts/build-static.js [outDir]

import { mkdirSync, rmSync, cpSync, writeFileSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { openDb, latestCollectedAt } from '../src/db/index.js';
import { getStoryViews, sortStoryViews, buildStoryDetail } from '../src/server/index.js';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const outDir = process.argv[2] ? join(process.cwd(), process.argv[2]) : join(root, 'dist');

const db = openDb(process.env.DB_PATH ?? join(root, 'data', 'app.db'));
const views = sortStoryViews(getStoryViews(db), 'mustknow');
if (views.length === 0) throw new Error('No stories in the DB — run `npm run collect` first.');

// The page shows "데이터 기준 …" from the newest collectedAt, not from build
// time: rebuilding without collecting must not make stale data look fresh.
const dataAsOf = latestCollectedAt(db);

rmSync(outDir, { recursive: true, force: true });
mkdirSync(join(outDir, 'data', 'story'), { recursive: true });
cpSync(join(root, 'public'), outDir, { recursive: true });

writeFileSync(join(outDir, 'data', 'stories.json'), JSON.stringify({ stories: views, dataAsOf }));
// The detail endpoint returns buildStoryDetail(view), not the list view —
// the frontend expects that richer shape.
for (const view of views) {
  writeFileSync(join(outDir, 'data', 'story', `${view.id}.json`), JSON.stringify(buildStoryDetail(view)));
}

// index.html uses absolute asset paths (/style.css, /app.js) because the
// server mounts at the domain root. Pages serves this under /<repo>/<dir>/,
// so rewrite them to relative and load the shim before app.js.
const html = readFileSync(join(root, 'public', 'index.html'), 'utf8')
  .replace(/(href|src)="\/([^"]+)"/g, '$1="./$2"')
  .replace('<script type="module" src="./app.js"></script>',
    '<script src="./static-api.js"></script>\n<script type="module" src="./app.js"></script>')
  .replace('<a href="./api/stories">/api/stories</a>', '<a href="./data/stories.json">수집된 스냅샷</a>');
writeFileSync(join(outDir, 'index.html'), html);

const generatedAt = new Date().toISOString();
writeFileSync(join(outDir, 'static-api.js'), `// Generated by scripts/build-static.js — do not edit.
// Answers the app's /api/... calls from the static snapshot in ./data.
// Sorting and category filtering mirror src/server/index.js, which normally
// does them server-side.
(function () {
  var BUILT_AT = ${JSON.stringify(generatedAt)};
  var DATA_AS_OF = ${JSON.stringify(dataAsOf)};
  var base = new URL('.', location.href);
  var cache = null;

  var SORT_VALUE = {
    viral: function (v) { return v.scores.viral.value; },
    credibility: function (v) { return v.scores.credibility.value; },
    impact: function (v) { return v.scores.impact.value; },
    recent: function (v) { return Date.parse(v.latestPublishedAt); },
    mustknow: function (v) { return v.scores.mustKnow.value; }
  };

  function json(body, status) {
    return new Response(JSON.stringify(body), {
      status: status || 200,
      headers: { 'Content-Type': 'application/json' }
    });
  }

  function loadAll() {
    if (cache) return cache;
    // GitHub Pages serves this with max-age=600, so a browser that visited
    // yesterday would keep showing yesterday's stories for ten minutes after
    // the daily deploy. 'no-cache' revalidates instead: a 304 when nothing
    // changed (cheap), the new snapshot the moment one lands.
    cache = fetch(new URL('data/stories.json', base), { cache: 'no-cache' }).then(function (r) { return r.json(); });
    return cache;
  }

  var nativeFetch = window.fetch.bind(window);

  window.fetch = function (input, init) {
    var raw = typeof input === 'string' ? input : (input && input.url) || '';
    if (raw.indexOf('/api/') === -1) return nativeFetch(input, init);

    var url = new URL(raw, location.href);
    var detail = url.pathname.match(/\\/api\\/stories\\/(.+)$/);

    if (detail) {
      var id = decodeURIComponent(detail[1]);
      return nativeFetch(new URL('data/story/' + encodeURIComponent(id) + '.json', base))
        .then(function (r) { return r.ok ? r.json().then(json) : json({ error: 'not found' }, 404); })
        .catch(function () { return json({ error: 'not found' }, 404); });
    }

    return loadAll().then(function (body) {
      var views = body.stories.slice();
      var category = url.searchParams.get('category');
      if (category) views = views.filter(function (v) { return v.category === category; });
      var key = SORT_VALUE[url.searchParams.get('sort')] || SORT_VALUE.mustknow;
      views.sort(function (a, b) { return key(b) - key(a); });
      return json({ stories: views, dataAsOf: body.dataAsOf || DATA_AS_OF, builtAt: BUILT_AT });
    });
  };
})();
`);

console.log(`Static build: ${views.length} stories -> ${outDir}`);
console.log(`Built at ${generatedAt}, data as of ${dataAsOf}`);
